global:
  scrape-interval: 15s
  evaluation-interval: 15s

rulefiles:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["local_host:9090"]
  
  - job_name: 'segundo-exporter'
    static_configs:
      - targets: ['local_host:7788']